// Auto-generated by scripts/generate-assets.js — do not edit manually
import { parseFontMetrics } from '@/view/NVFont'
import metricsJson from './Ubuntu.json'
import atlasUrl from './Ubuntu.png'
import type { NVFontData } from '@/NVTypes'

export const ubuntu: NVFontData = {
  metrics: parseFontMetrics(metricsJson),
  atlasUrl,
}
