// Auto-generated by scripts/generate-assets.js — do not edit manually

import type { NVFontData } from "@/NVTypes";
import { parseFontMetrics } from "@/view/NVFont";
import metricsJson from "./Ubuntu.json";
import atlasUrl from "./Ubuntu.png";

export const ubuntu: NVFontData = {
  metrics: parseFontMetrics(metricsJson),
  atlasUrl,
};
