/**
 * Auto-generates TypeScript wrapper files for font and matcap assets.
 *
 * Fonts:  each JSON+PNG pair in src/assets/fonts/ produces a wrapper .ts
 * Matcaps: each JPG/PNG image in src/assets/matcaps/ produces a wrapper .ts
 * Both directories get an auto-generated index.ts with re-exports.
 *
 * Usage:  node scripts/generate-assets.js
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, parse } from 'node:path'

const FONTS_DIR = 'src/assets/fonts'
const MATCAPS_DIR = 'src/assets/matcaps'
const HEADER =
  '// Auto-generated by scripts/generate-assets.js — do not edit manually\n'

function lcFirst(s) {
  return s.charAt(0).toLowerCase() + s.slice(1)
}

function unchanged(path, content) {
  try {
    return readFileSync(path, 'utf8') === content
  } catch {
    return false
  }
}

function writeIfChanged(path, content) {
  if (unchanged(path, content)) return false
  writeFileSync(path, content)
  return true
}

function generateFonts() {
  // Scan the fonts directory for JSON+PNG pairs and build the public
  // `index.ts` barrel. These wrappers ship in the published library bundle.
  const siblingFiles = readdirSync(FONTS_DIR)
  const jsonFiles = siblingFiles.filter((f) => f.endsWith('.json')).sort()
  const exportNames = []
  let changed = 0

  for (const jsonFile of jsonFiles) {
    const { name: baseName } = parse(jsonFile)
    const pngFile = `${baseName}.png`
    if (!siblingFiles.includes(pngFile)) {
      console.warn(`  Warning: Missing ${pngFile} for ${jsonFile}, skipping`)
      continue
    }
    const exportName = lcFirst(baseName)
    const content = `${HEADER}import type { NVFontData } from '@/NVTypes'
import { parseFontMetrics } from '@/view/NVFont'
import metricsJson from './${jsonFile}'
import atlasUrl from './${pngFile}'

export const ${exportName}: NVFontData = {
  metrics: parseFontMetrics(metricsJson),
  atlasUrl,
}
`
    const wrapperPath = join(FONTS_DIR, `${exportName}.ts`)
    if (writeIfChanged(wrapperPath, content)) {
      console.log(`  Generated ${wrapperPath}`)
      changed++
    }
    exportNames.push(exportName)
  }

  const indexContent = `${HEADER}// biome-ignore lint/performance/noBarrelFile: auto-generated barrel\n${exportNames.map((n) => `export { ${n} } from './${n}'`).join('\n')}\n`
  if (writeIfChanged(join(FONTS_DIR, 'index.ts'), indexContent)) {
    console.log('  Generated index.ts')
    changed++
  }
  return changed
}

function generateMatcaps() {
  const files = readdirSync(MATCAPS_DIR)
  const imageFiles = files.filter((f) => /\.(jpg|png)$/i.test(f)).sort()
  const exports = []
  let changed = 0

  for (const imageFile of imageFiles) {
    const { name: baseName } = parse(imageFile)
    const exportName = lcFirst(baseName)
    const wrapperFile = `${exportName}.ts`

    const content = `${HEADER}import url from './${imageFile}'
export const ${exportName} = url
`
    if (writeIfChanged(join(MATCAPS_DIR, wrapperFile), content)) {
      console.log(`  Generated ${wrapperFile}`)
      changed++
    }
    exports.push(`export { ${exportName} } from './${exportName}'`)
  }

  const indexContent = `${HEADER}// biome-ignore lint/performance/noBarrelFile: auto-generated barrel\n${exports.join('\n')}\n`
  if (writeIfChanged(join(MATCAPS_DIR, 'index.ts'), indexContent)) {
    console.log('  Generated index.ts')
    changed++
  }

  return changed
}

console.log('Generating asset wrappers...')
const fontChanges = generateFonts()
const matcapChanges = generateMatcaps()

if (fontChanges + matcapChanges === 0) {
  console.log('  All wrappers up to date.')
} else {
  console.log(`  Done (${fontChanges + matcapChanges} file(s) updated).`)
}
