"""ipyniivue — Jupyter widget for NiiVue medical-image visualization.

This package wraps the @niivue/niivue JavaScript library as an anywidget.
Most of the API surface (reactive properties, command methods, event names)
is auto-generated by `scripts/codegen.ts` from the TypeScript source — see
`_generated.py`. The user-facing class lives in `widget.py`.
"""

from __future__ import annotations

from ipyniivue._generated import NIIVUE_EVENT_NAMES
from ipyniivue.widget import NiiVue

__all__ = ["NIIVUE_EVENT_NAMES", "NiiVue"]
