# This file is auto-generated by scripts/codegen.ts.
# Do not edit by hand — re-run `bunx nx codegen ipyniivue`.
# Source: packages/niivue/src/NVControlBase.ts @ niivue 1.0.0-rc.1
# Generated at: 2026-04-26T17:19:46.143Z

# ruff: noqa
# mypy: ignore-errors

from __future__ import annotations

from typing import Any

import anywidget
import traitlets


# Set of event names that JS may dispatch to Python. The
# hand-written `widget.NiiVue.on()` method validates against this.
NIIVUE_EVENT_NAMES: frozenset[str] = frozenset({
    "angleCompleted",
    "annotationAdded",
    "annotationChanged",
    "annotationRemoved",
    "azimuthElevationChange",
    "canvasResize",
    "change",
    "clipPlaneChange",
    "colormapAdded",
    "documentLoaded",
    "dragRelease",
    "drawingChanged",
    "drawingEnabled",
    "frameChange",
    "locationChange",
    "measurementCompleted",
    "meshLoaded",
    "meshRemoved",
    "meshUpdated",
    "penValueChanged",
    "pointerUp",
    "sliceTypeChange",
    "viewAttached",
    "viewDestroyed",
    "volumeLoaded",
    "volumeOrderChanged",
    "volumeRemoved",
    "volumeUpdated",
})


class _GeneratedNiiVue(anywidget.AnyWidget):
    """Auto-generated reactive properties and command methods.

    Mirrors NiiVueGPU @ niivue 1.0.0-rc.1.

    Reactive properties are kept in sync with the JS view via
    anywidget. Methods send command messages over the same
    channel; for now they are fire-and-forget. A future phase
    will introduce request/response semantics for methods that
    return data.
    """

    # ─── Reactive properties (read+write, synced) ───────────────
    annotation_active_group = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    annotation_active_label = traitlets.Float(None, allow_none=True).tag(sync=True)
    annotation_brush_radius = traitlets.Float(None, allow_none=True).tag(sync=True)
    annotation_is_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_is_erasing = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_is_visible_in_3d = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_tool = traitlets.Enum(["freehand", "ellipse", "rectangle", "line", "arrow", "measureEllipse", "measureRect", "measureLine", "circle", "measureCircle"], None, allow_none=True).tag(sync=True)
    azimuth = traitlets.Float(None, allow_none=True).tag(sync=True)
    background_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)
    clip_plane_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    crosshair_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    crosshair_gap = traitlets.Float(None, allow_none=True).tag(sync=True)
    crosshair_pos = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=3, maxlen=3, allow_none=True).tag(sync=True)
    crosshair_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    device_pixel_ratio = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_colormap = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    draw_is_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    draw_is_fill_overwriting = traitlets.Bool(None, allow_none=True).tag(sync=True)
    draw_opacity = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_pen_size = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_pen_value = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_rim_opacity = traitlets.Float(None, allow_none=True).tag(sync=True)
    elevation = traitlets.Float(None, allow_none=True).tag(sync=True)
    font_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    font_min_size = traitlets.Float(None, allow_none=True).tag(sync=True)
    font_scale = traitlets.Float(None, allow_none=True).tag(sync=True)
    force_device_pixel_ratio = traitlets.Float(None, allow_none=True).tag(sync=True)
    gamma = traitlets.Float(None, allow_none=True).tag(sync=True)
    graph_is_range_cal_min_max = traitlets.Bool(None, allow_none=True).tag(sync=True)
    graph_normalize_values = traitlets.Bool(None, allow_none=True).tag(sync=True)
    hero_fraction = traitlets.Float(None, allow_none=True).tag(sync=True)
    hero_slice_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    is_3d_crosshair_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_clip_plane_cutaway = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_colorbar_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_cross_lines_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_drag_drop_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_equal_size = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_graph_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_legend_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_measure_units_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_mosaic_centered = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_orientation_text_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_orient_cube_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_position_in_mm = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_radiological = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_ruler_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_snap_to_voxel_centers = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_thumbnail_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_yoked_3d_to_2d_zoom = traitlets.Bool(None, allow_none=True).tag(sync=True)
    measure_line_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    measure_text_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    mesh_thickness_on_2d = traitlets.Float(None, allow_none=True).tag(sync=True)
    mesh_x_ray = traitlets.Float(None, allow_none=True).tag(sync=True)
    mosaic_string = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    multiplanar_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    pan_2_dxyzmm = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)
    placeholder_text = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    primary_drag_mode = traitlets.Float(None, allow_none=True).tag(sync=True)
    ruler_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    scale_multiplier = traitlets.Float(None, allow_none=True).tag(sync=True)
    secondary_drag_mode = traitlets.Float(None, allow_none=True).tag(sync=True)
    selection_box_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    show_render = traitlets.Float(None, allow_none=True).tag(sync=True)
    slice_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    thumbnail_url = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    tile_margin = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_alpha_shader = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_illumination = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_is_alpha_clip_dark = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_background_masking = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_nearest_interpolation = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_v1_slice_shader = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_matcap = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    volume_outline_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_paqd_uniforms = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)

    # ─── Read-only properties (synced from JS to Python) ────────
    backend = traitlets.Enum(["webgpu", "webgl2"], None, allow_none=True).tag(sync=True, o2py_readonly=True)
    colormaps = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    drawing_colormaps = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    is_anti_alias = traitlets.Bool(None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_shaders = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_write_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    selected_annotation = traitlets.Unicode(None, allow_none=True).tag(sync=True, o2py_readonly=True)
    volume_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    volume_transforms = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    """Get list of available volume transform names."""
    volume_write_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)

    # ─── Command methods (fire-and-forget) ──────────────────────
    def add_annotation(self, annotation: Any) -> None:
        self.send({"cmd": "addAnnotation", "args": [annotation]})

    async def add_colormap(self, name: Any, cmap: Any) -> Any:
        """Register a colormap by name so it becomes available to
        `setVolume({ colormap: name })`, `nv1.colormaps`, colorbars, mesh
        layers, and so on. Use this to add user-defined LUTs at runtime.
        Re-registering an existing name replaces the entry. Does not trigger a
        redraw — the colormap is inert until a volume references it.
        
        Label colormaps (for atlas volumes with per-index labels) have their
        own registration path: `setColormapLabel()` / `setColormapLabelFromUrl()`.
        """
        return await self._request("addColormap", [name, cmap])

    def add_colormap_from_url(self, url: Any, name: Any = None) -> None:
        """Fetch a colormap JSON (`{ R, G, B, A?, I? }`) from a URL or `File` and
        register it under `name`. When `name` is omitted, it is derived from
        the source filename; callers passing an un-nameable source (e.g.
        `?query-only`) should supply `name` explicitly — an empty derived
        name throws.
        """
        self.send({"cmd": "addColormapFromUrl", "args": [url, name]})

    def add_image(self, path_or_file: Any, options: Any = None) -> None:
        self.send({"cmd": "addImage", "args": [path_or_file, options]})

    def add_mesh(self, mesh: Any) -> None:
        self.send({"cmd": "addMesh", "args": [mesh]})

    def add_mesh_layer(self, mesh_index: Any, layer_opts: Any) -> None:
        """Add a scalar overlay layer to a mesh.
        """
        self.send({"cmd": "addMeshLayer", "args": [mesh_index, layer_opts]})

    def add_volume(self, volume: Any) -> None:
        self.send({"cmd": "addVolume", "args": [volume]})

    def annotation_redo(self) -> None:
        self.send({"cmd": "annotationRedo", "args": []})

    def annotation_undo(self) -> None:
        self.send({"cmd": "annotationUndo", "args": []})

    def attach_to(self, id: Any, is_anti_alias: Any = None) -> None:
        self.send({"cmd": "attachTo", "args": [id, is_anti_alias]})

    def attach_to_canvas(self, canvas: Any, is_anti_alias: Any = None) -> None:
        self.send({"cmd": "attachToCanvas", "args": [canvas, is_anti_alias]})

    def broadcast_to(self, targets: Any = None, opts: Any = None) -> None:
        """Sync the scene controls (orientation, crosshair location, etc.) from one NiiVue instance to others.
        """
        self.send({"cmd": "broadcastTo", "args": [targets, opts]})

    def clear_annotations(self) -> None:
        self.send({"cmd": "clearAnnotations", "args": []})

    def clear_custom_layout(self) -> None:
        """Clear any custom layout and revert to built-in layout modes.
        """
        self.send({"cmd": "clearCustomLayout", "args": []})

    def clear_measurements(self) -> None:
        self.send({"cmd": "clearMeasurements", "args": []})

    def close_drawing(self) -> None:
        self.send({"cmd": "closeDrawing", "args": []})

    def create_empty_drawing(self) -> None:
        self.send({"cmd": "createEmptyDrawing", "args": []})

    async def create_extension_context(self) -> Any:
        """Create an extension context for interacting with this NiiVue instance.
        
        The context provides a stable API surface for extensions: live data
        accessors, event subscriptions (including high-level slice pointer events),
        safe write-back actions, and coordinate transform utilities.
        
        Call `context.dispose()` when the extension is deactivated to remove all
        event listeners registered through the context.
        
        Multiple contexts can coexist — each tracks its own subscriptions.
        """
        return await self._request("createExtensionContext", [])

    def create_on_location_change(self, ax_cor_sag: Any = None) -> None:
        self.send({"cmd": "createOnLocationChange", "args": [ax_cor_sag]})

    def destroy(self) -> None:
        self.send({"cmd": "destroy", "args": []})

    def draw_scene(self, needs_sync: Any = None) -> None:
        self.send({"cmd": "drawScene", "args": [needs_sync]})

    def draw_undo(self) -> None:
        self.send({"cmd": "drawUndo", "args": []})

    def enforce_backend_availability(self) -> None:
        self.send({"cmd": "enforceBackendAvailability", "args": []})

    async def get_annotations_json(self) -> Any:
        return await self._request("getAnnotationsJSON", [])

    async def get_clip_plane_depth_azi_elev(self, clip_plane_index: Any = None) -> Any:
        return await self._request("getClipPlaneDepthAziElev", [clip_plane_index])

    async def get_crosshair_pos(self) -> Any:
        return await self._request("getCrosshairPos", [])

    async def get_frame_4d(self, id: Any) -> Any:
        """Get the current 4D frame index for a volume.
        """
        return await self._request("getFrame4D", [id])

    async def get_mesh_shader(self, mesh_index: Any) -> Any:
        return await self._request("getMeshShader", [mesh_index])

    async def get_tract_groups(self, mesh_index: Any) -> Any:
        """Get the group names for a tract mesh.
        Returns an empty array if the mesh is not a tract or has no groups.
        """
        return await self._request("getTractGroups", [mesh_index])

    async def get_volume_transform_info(self, name: Any) -> Any:
        """Get metadata for a specific volume transform (options, description, resultDefaults).
        """
        return await self._request("getVolumeTransformInfo", [name])

    async def has_colormap(self, name: Any) -> Any:
        """Case-insensitive existence check for a registered colormap. Accepts
        whatever casing the caller has on hand (e.g. a lowercased `<select>`
        value) and compares against the canonical stored name. Prefer this
        over `nv1.colormaps.includes(...)` — it handles the first-letter
        canonicalization that `addColormap` and the filesystem auto-loader
        apply internally.
        """
        return await self._request("hasColormap", [name])

    def load_annotations_json(self, json: Any) -> None:
        self.send({"cmd": "loadAnnotationsJSON", "args": [json]})

    def load_deferred_4d_volumes(self, id: Any) -> None:
        """Load all remaining frames for a 4D volume that was opened with limitFrames4D.
        Re-fetches the complete file and replaces the truncated image data.
        """
        self.send({"cmd": "loadDeferred4DVolumes", "args": [id]})

    def load_document(self, source: Any) -> None:
        self.send({"cmd": "loadDocument", "args": [source]})

    async def load_drawing(self, source: Any) -> Any:
        return await self._request("loadDrawing", [source])

    def load_image(self, path_or_file: Any, options: Any = None) -> None:
        self.send({"cmd": "loadImage", "args": [path_or_file, options]})

    async def load_img_v1(self, volume_index: Any, is_flip_x: Any = None, is_flip_y: Any = None, is_flip_z: Any = None) -> Any:
        """Convert a float32 3-frame volume to V1 (eigenvector) RGBA representation.
        For formats like AFNI that lack NIfTI intent codes, this provides explicit
        conversion of vector field data (dim4=3, float32) to sign-encoded RGBA.
        """
        return await self._request("loadImgV1", [volume_index, is_flip_x, is_flip_y, is_flip_z])

    def load_matcap(self, matcap_name: Any) -> None:
        self.send({"cmd": "loadMatcap", "args": [matcap_name]})

    def load_meshes(self, meshes: Any) -> None:
        self.send({"cmd": "loadMeshes", "args": [meshes]})

    def load_volumes(self, volumes: Any) -> None:
        self.send({"cmd": "loadVolumes", "args": [volumes]})

    def move_crosshair_in_vox(self, di: Any, dj: Any, dk: Any) -> None:
        self.send({"cmd": "moveCrosshairInVox", "args": [di, dj, dk]})

    def move_volume_down(self, volume_index: Any) -> None:
        """Move a volume down one index position in the stack of loaded volumes (toward the background).
        """
        self.send({"cmd": "moveVolumeDown", "args": [volume_index]})

    def move_volume_to_bottom(self, volume_index: Any) -> None:
        """Move a volume to the bottom position in the stack of loaded volumes (index 0, background).
        """
        self.send({"cmd": "moveVolumeToBottom", "args": [volume_index]})

    def move_volume_to_top(self, volume_index: Any) -> None:
        """Move a volume to the top position in the stack of loaded volumes (last index, top layer).
        """
        self.send({"cmd": "moveVolumeToTop", "args": [volume_index]})

    def move_volume_up(self, volume_index: Any) -> None:
        """Move a volume up one index position in the stack of loaded volumes (toward the top layer).
        """
        self.send({"cmd": "moveVolumeUp", "args": [volume_index]})

    def recalculate_cal_min_max(self, volume_index: Any, frame: Any = None) -> None:
        """Recalculate robust cal_min/cal_max for a specific 4D frame (or the current frame).
        Updates the volume's calibration range and triggers a GPU update.
        """
        self.send({"cmd": "recalculateCalMinMax", "args": [volume_index, frame]})

    def refresh_drawing(self) -> None:
        """Mark the drawing texture as dirty and schedule a redraw.
        The expensive bitmap→RGBA conversion and GPU upload are deferred to
        the next animation frame, so rapid pointermove events only pay the
        cost once per frame.
        """
        self.send({"cmd": "refreshDrawing", "args": []})

    def register_volume_transform(self, transform: Any) -> None:
        """Register an external volume transform at runtime.
        External transforms manage their own Web Worker execution internally.
        """
        self.send({"cmd": "registerVolumeTransform", "args": [transform]})

    async def reinitialize_view(self, options: Any = None) -> Any:
        return await self._request("reinitializeView", [options])

    def remove_all_meshes(self) -> None:
        self.send({"cmd": "removeAllMeshes", "args": []})

    def remove_all_volumes(self) -> None:
        self.send({"cmd": "removeAllVolumes", "args": []})

    def remove_annotation(self, id: Any) -> None:
        self.send({"cmd": "removeAnnotation", "args": [id]})

    def remove_mesh(self, mesh_index: Any) -> None:
        self.send({"cmd": "removeMesh", "args": [mesh_index]})

    def remove_mesh_layer(self, mesh_index: Any, layer_index: Any) -> None:
        """Remove a scalar overlay layer from a mesh.
        """
        self.send({"cmd": "removeMeshLayer", "args": [mesh_index, layer_index]})

    def resize(self) -> None:
        self.send({"cmd": "resize", "args": []})

    async def save_bitmap(self, filename: Any = None, quality: Any = None) -> Any:
        return await self._request("saveBitmap", [filename, quality])

    def save_document(self, filename: Any = None) -> None:
        self.send({"cmd": "saveDocument", "args": [filename]})

    async def save_drawing(self, filename: Any = None) -> Any:
        return await self._request("saveDrawing", [filename])

    def save_mesh(self, mesh_index: Any, filename: Any = None, options: Any = None) -> None:
        self.send({"cmd": "saveMesh", "args": [mesh_index, filename, options]})

    async def save_volume(self, options: Any = None) -> Any:
        """Save voxel-based image to disk.
        """
        return await self._request("saveVolume", [options])

    def select_annotation(self, id: Any) -> None:
        self.send({"cmd": "selectAnnotation", "args": [id]})

    async def serialize_document(self) -> Any:
        """Return the current scene serialized as an NVD document (CBOR-encoded Uint8Array).
        """
        return await self._request("serializeDocument", [])

    def set_bounds(self, bounds: Any) -> None:
        """Update the drawing bounds for this Niivue instance.
        Coordinates use y=0 at bottom, y=1 at top (GL convention).
        """
        self.send({"cmd": "setBounds", "args": [bounds]})

    def set_clip_plane(self, depth_azimuth_elevation: Any) -> None:
        self.send({"cmd": "setClipPlane", "args": [depth_azimuth_elevation]})

    def set_clip_plane_depth_azi_elev(self, depth: Any, azimuth: Any, elevation: Any, clip_plane_index: Any = None) -> None:
        self.send({"cmd": "setClipPlaneDepthAziElev", "args": [depth, azimuth, elevation, clip_plane_index]})

    def set_clip_planes(self, depth_azi_elevs: Any) -> None:
        self.send({"cmd": "setClipPlanes", "args": [depth_azi_elevs]})

    def set_colormap_label(self, volume_index: Any, cmap: Any) -> None:
        """Set a label colormap on a volume (e.g., atlas/parcellation).
        Converts the ColorMap definition to an LUT and attaches it to the volume.
        When set, the orient shader uses nearest-neighbor label lookup instead of
        continuous colormap interpolation, and locationChange events include label names.
        """
        self.send({"cmd": "setColormapLabel", "args": [volume_index, cmap]})

    def set_colormap_label_from_url(self, volume_index: Any, url: Any) -> None:
        """Fetch a label colormap JSON from a URL or File and apply it to a volume.
        The JSON should contain R, G, B arrays and optional labels/I arrays.
        """
        self.send({"cmd": "setColormapLabelFromUrl", "args": [volume_index, url]})

    def set_connectome_options(self, mesh_index: Any, options: Any) -> None:
        """Update connectome extrusion/display options and re-extrude.
        """
        self.send({"cmd": "setConnectomeOptions", "args": [mesh_index, options]})

    def set_crosshair_pos(self, pos: Any) -> None:
        self.send({"cmd": "setCrosshairPos", "args": [pos]})

    def set_drag_mode(self, mode: Any) -> None:
        self.send({"cmd": "setDragMode", "args": [mode]})

    async def set_font(self, font: Any) -> Any:
        """Swap the active font atlas. The font is infrastructure-level configuration
        (GPU-owned atlas texture + metrics map), so switching requires a full view
        rebuild — use this method instead of mutating `opts.font` directly.
        """
        return await self._request("setFont", [font])

    async def set_font_from_url(self, urls: Any) -> Any:
        """Fetch an MSDF font atlas (PNG + JSON metrics pair) from URLs and swap
        it in as the active font. Useful for loading fonts that are not bundled
        with the library (e.g. the community atlases at
        https://github.com/niivue/fonts). The PNG URL is stored verbatim and
        used as the GPU atlas texture source.
        
        On failure (metrics fetch, view rebuild, or atlas texture upload)
        the previous font is restored so the view isn't left half-initialized.
        The original error is re-thrown after recovery.
        """
        return await self._request("setFontFromUrl", [urls])

    def set_frame_4d(self, id: Any, frame: Any) -> None:
        """Set the current 4D frame for a volume.
        """
        self.send({"cmd": "setFrame4D", "args": [id, frame]})

    def set_mesh(self, mesh_index: Any, options: Any) -> None:
        """Update display properties of a loaded mesh.
        Accepts any subset of mesh display options (opacity, shaderType, color, etc.)
        and triggers a single GPU update.
        """
        self.send({"cmd": "setMesh", "args": [mesh_index, options]})

    def set_mesh_layer_frame_4d(self, mesh_index: Any, layer_index: Any, frame: Any) -> None:
        """Set the current 4D frame for a mesh layer.
        """
        self.send({"cmd": "setMeshLayerFrame4D", "args": [mesh_index, layer_index, frame]})

    def set_mesh_layer_property(self, mesh_index: Any, layer_index: Any, options: Any) -> None:
        """Update properties of a mesh layer (colormap, cal_min, cal_max, opacity, etc.).
        Triggers recompositing and GPU update.
        """
        self.send({"cmd": "setMeshLayerProperty", "args": [mesh_index, layer_index, options]})

    def set_modulation_image(self, target_id: Any, modulator_id: Any) -> None:
        """Set a modulation image for a target volume.
        The modulator's intensity scales the target volume's brightness and opacity.
        """
        self.send({"cmd": "setModulationImage", "args": [target_id, modulator_id]})

    def set_tract_options(self, mesh_index: Any, options: Any) -> None:
        """Update tract tessellation/display options and re-tessellate.
        """
        self.send({"cmd": "setTractOptions", "args": [mesh_index, options]})

    def set_volume(self, volume_index: Any, options: Any) -> None:
        """Update display properties of a loaded volume.
        Accepts any subset of volume display options (colormap, opacity, cal_min, etc.)
        and triggers a single GPU update.
        """
        self.send({"cmd": "setVolume", "args": [volume_index, options]})

    def update_gl_volume(self) -> None:
        self.send({"cmd": "updateGLVolume", "args": []})

    def use_loader(self, converter: Any, from_ext: Any, to_ext: Any) -> None:
        """Register an external format loader.
        The converter function receives raw file bytes and returns bytes in a known format.
        """
        self.send({"cmd": "useLoader", "args": [converter, from_ext, to_ext]})

    async def vox2frac(self, vox: Any) -> Any:
        """Convert RAS voxel coordinates to scene fraction [0,1].
        Uses the background volume's matRAS for the vox→mm conversion.
        """
        return await self._request("vox2frac", [vox])


