# This file is auto-generated by scripts/codegen.ts.
# Do not edit by hand; re-run `bunx nx codegen ipyniivue`.
# Source: packages/niivue/src/NVControlBase.ts @ niivue 1.0.0-rc.3

# ruff: noqa
# mypy: ignore-errors

from __future__ import annotations

from typing import Any

import anywidget
import traitlets


_UNSET = object()
_JS_UNDEFINED = {"__ipyniivue_undefined__": True}


def _make_args(*values: Any) -> list[Any]:
    """Build JSON-safe JS call args while preserving omitted optionals."""
    trimmed = list(values)
    while trimmed and trimmed[-1] is _UNSET:
        trimmed.pop()
    return [_JS_UNDEFINED if value is _UNSET else value for value in trimmed]


# Set of event names that JS may dispatch to Python. The
# hand-written `widget.NiiVue.on()` method validates against this.
# Events that the JS template intentionally suppresses (high-frequency
# layout ticks like `canvasResize`) are filtered out so subscribing to
# them raises instead of silently never firing.
NIIVUE_EVENT_NAMES: frozenset[str] = frozenset({
    "angleCompleted",
    "annotationAdded",
    "annotationChanged",
    "annotationRemoved",
    "azimuthElevationChange",
    "change",
    "clipPlaneChange",
    "colormapAdded",
    "documentLoaded",
    "dragRelease",
    "drawingChanged",
    "drawingEnabled",
    "frameChange",
    "locationChange",
    "measurementCompleted",
    "meshLoaded",
    "meshRemoved",
    "meshUpdated",
    "penValueChanged",
    "pointerUp",
    "sliceTypeChange",
    "volumeLoaded",
    "volumeOrderChanged",
    "volumeRemoved",
    "volumeUpdated",
})


class _GeneratedNiiVue(anywidget.AnyWidget):
    """Auto-generated reactive properties and command methods.

    Mirrors NiiVueGPU @ niivue 1.0.0-rc.3.

    Reactive properties are kept in sync with the JS view via
    anywidget. Methods send command messages over the same
    channel. Void-returning methods are fire-and-forget;
    value-returning methods use request/response correlation
    and should return small JSON-serializable payloads.
    """

    # Synthetic inbox for Python-to-JS commands. Python may queue
    # commands immediately after display(nv), before the browser view
    # has loaded this widget module and registered msg:custom handlers.
    # Storing commands as synced state makes that cold-start path
    # durable; JS processes any unhandled seq values after initialize.
    _msg_inbox = traitlets.List([]).tag(sync=True)

    # Highest seq from `_msg_inbox` that JS has fully drained. JS sets
    # this after each inbox-processing pass; Python observes it and
    # prunes acknowledged items so a session's worth of buffer payloads
    # does not pin base64 strings in trait state forever.
    _msg_inbox_ack = traitlets.Int(0).tag(sync=True)

    # Synthetic outbox for JS-to-Python messages. anywidget 0.9.x +
    # ipywidgets 8.x do not reliably route `model.send()` from JS
    # through Python's `on_msg` callbacks in our setup; the
    # message succeeds JS-side but vanishes before reaching the
    # Python widget. As a workaround, JS writes outbound
    # messages here (a Dict trait with a monotonic seq), Python
    # observes `change:_msg_outbox`, and `widget.NiiVue` routes
    # the body through `_dispatch_message`. State-update is the
    # same channel the seed-step uses, which is verifiably
    # reliable end-to-end.
    _msg_outbox = traitlets.Dict({}).tag(sync=True)

    # Reactive properties (read+write, synced)
    annotation_active_group = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    annotation_active_label = traitlets.Float(None, allow_none=True).tag(sync=True)
    annotation_brush_radius = traitlets.Float(None, allow_none=True).tag(sync=True)
    annotation_is_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_is_erasing = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_is_visible_in_3d = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_tool = traitlets.Enum(["freehand", "ellipse", "rectangle", "line", "arrow", "measureEllipse", "measureRect", "measureLine", "circle", "measureCircle"], None, allow_none=True).tag(sync=True)
    azimuth = traitlets.Float(None, allow_none=True).tag(sync=True)
    background_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)
    clip_plane_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    crosshair_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    crosshair_gap = traitlets.Float(None, allow_none=True).tag(sync=True)
    crosshair_pos = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=3, maxlen=3, allow_none=True).tag(sync=True)
    crosshair_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    device_pixel_ratio = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_colormap = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    draw_is_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    draw_is_fill_overwriting = traitlets.Bool(None, allow_none=True).tag(sync=True)
    draw_opacity = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_pen_size = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_pen_value = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_rim_opacity = traitlets.Float(None, allow_none=True).tag(sync=True)
    elevation = traitlets.Float(None, allow_none=True).tag(sync=True)
    font_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    font_min_size = traitlets.Float(None, allow_none=True).tag(sync=True)
    font_scale = traitlets.Float(None, allow_none=True).tag(sync=True)
    force_device_pixel_ratio = traitlets.Float(None, allow_none=True).tag(sync=True)
    gamma = traitlets.Float(None, allow_none=True).tag(sync=True)
    graph_is_range_cal_min_max = traitlets.Bool(None, allow_none=True).tag(sync=True)
    graph_normalize_values = traitlets.Bool(None, allow_none=True).tag(sync=True)
    hero_fraction = traitlets.Float(None, allow_none=True).tag(sync=True)
    hero_slice_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    is_3d_crosshair_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_clip_plane_cutaway = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_colorbar_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_cross_lines_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_drag_drop_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_equal_size = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_graph_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_legend_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_measure_units_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_mosaic_centered = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_orientation_text_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_orient_cube_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_position_in_mm = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_radiological = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_ruler_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_snap_to_voxel_centers = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_thumbnail_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_yoked_3d_to_2d_zoom = traitlets.Bool(None, allow_none=True).tag(sync=True)
    measure_line_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    measure_text_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    mesh_thickness_on_2d = traitlets.Float(None, allow_none=True).tag(sync=True)
    mesh_x_ray = traitlets.Float(None, allow_none=True).tag(sync=True)
    mosaic_string = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    multiplanar_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    pan_2_dxyzmm = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)
    placeholder_text = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    primary_drag_mode = traitlets.Float(None, allow_none=True).tag(sync=True)
    ruler_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    scale_multiplier = traitlets.Float(None, allow_none=True).tag(sync=True)
    secondary_drag_mode = traitlets.Float(None, allow_none=True).tag(sync=True)
    selection_box_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    show_render = traitlets.Float(None, allow_none=True).tag(sync=True)
    slice_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    thumbnail_url = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    tile_margin = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_alpha_shader = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_illumination = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_is_alpha_clip_dark = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_background_masking = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_nearest_interpolation = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_v1_slice_shader = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_matcap = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    volume_outline_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_paqd_uniforms = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)

    # Read-only properties (synced from JS to Python)
    backend = traitlets.Enum(["webgpu", "webgl2"], None, allow_none=True).tag(sync=True, o2py_readonly=True)
    colormaps = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    drawing_colormaps = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    is_anti_alias = traitlets.Bool(None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_shaders = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_write_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    selected_annotation = traitlets.Unicode(None, allow_none=True).tag(sync=True, o2py_readonly=True)
    volume_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    volume_transforms = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    """Get list of available volume transform names."""
    volume_write_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)

    # Command methods
    def add_annotation(self, annotation: Any) -> None:
        self.send({"cmd": "addAnnotation", "args": _make_args(annotation)})

    async def add_colormap(self, name: Any, cmap: Any) -> Any:
        """Register a colormap by name so it becomes available to `setVolume({ colormap: name })`, `nv1.colormaps`, colorbars, mesh layers, and so on.

        Use this to add user-defined LUTs at runtime.
        Re-registering an existing name replaces the entry. Does not trigger a
        redraw — the colormap is inert until a volume references it.

        Label colormaps (for atlas volumes with per-index labels) have their
        own registration path: `setColormapLabel()` / `setColormapLabelFromUrl()`.

        Parameters
        ----------
        name : string
        cmap : Pick<ColorMap, \"R\" | \"G\" | \"B\"> & Partial<Pick<ColorMap, \"A\" | \"I\" | \"labels\">>

        Returns
        -------
        string
            The canonical name under which the colormap was stored
            (first letter upper-cased), which is the form visible in `nv1.colormaps`
            and the `colormapAdded` event detail.
        """
        return await self._request("addColormap", _make_args(name, cmap))

    def add_colormap_from_url(self, url: Any, name: Any = _UNSET) -> None:
        """Fetch a colormap JSON (`{ R, G, B, A?, I? }`) from a URL or `File` and register it under `name`.

        When `name` is omitted, it is derived from
        the source filename; callers passing an un-nameable source (e.g.
        `?query-only`) should supply `name` explicitly — an empty derived
        name throws.

        Parameters
        ----------
        url : string | File
        name : string | undefined
        """
        self.send({"cmd": "addColormapFromUrl", "args": _make_args(url, name)})

    def add_image(self, path_or_file: Any, options: Any = _UNSET) -> None:
        self.send({"cmd": "addImage", "args": _make_args(path_or_file, options)})

    def add_mesh(self, mesh: Any) -> None:
        self.send({"cmd": "addMesh", "args": _make_args(mesh)})

    def add_mesh_layer(self, mesh_index: Any, layer_opts: Any) -> None:
        """Add a scalar overlay layer to a mesh.

        Parameters
        ----------
        mesh_index : number
        layer_opts : MeshLayerFromUrlOptions
        """
        self.send({"cmd": "addMeshLayer", "args": _make_args(mesh_index, layer_opts)})

    def add_volume(self, volume: Any) -> None:
        self.send({"cmd": "addVolume", "args": _make_args(volume)})

    def annotation_redo(self) -> None:
        self.send({"cmd": "annotationRedo", "args": []})

    def annotation_undo(self) -> None:
        self.send({"cmd": "annotationUndo", "args": []})

    def apply_volume_transform(self, volume_index: Any, transform: Any) -> None:
        self.send({"cmd": "applyVolumeTransform", "args": _make_args(volume_index, transform)})

    def attach_to(self, id: Any, is_anti_alias: Any = _UNSET) -> None:
        self.send({"cmd": "attachTo", "args": _make_args(id, is_anti_alias)})

    def broadcast_to(self, targets: Any = _UNSET, opts: Any = _UNSET) -> None:
        """Sync the scene controls (orientation, crosshair location, etc.) from one NiiVue instance to others.

        Parameters
        ----------
        targets : default | default[] | undefined
            the other NiiVue instance(s) to broadcast to, or omit to clear sync
        opts : SyncOpts
            which properties to sync (default: { '2d': true, '3d': true })
        """
        self.send({"cmd": "broadcastTo", "args": _make_args(targets, opts)})

    def clear_annotations(self) -> None:
        self.send({"cmd": "clearAnnotations", "args": []})

    def clear_custom_layout(self) -> None:
        """Clear any custom layout and revert to built-in layout modes.
        """
        self.send({"cmd": "clearCustomLayout", "args": []})

    def clear_measurements(self) -> None:
        self.send({"cmd": "clearMeasurements", "args": []})

    def close_drawing(self) -> None:
        self.send({"cmd": "closeDrawing", "args": []})

    def create_empty_drawing(self) -> None:
        self.send({"cmd": "createEmptyDrawing", "args": []})

    def create_on_location_change(self, ax_cor_sag: Any = _UNSET) -> None:
        self.send({"cmd": "createOnLocationChange", "args": _make_args(ax_cor_sag)})

    def destroy(self) -> None:
        self.send({"cmd": "destroy", "args": []})

    def draw_scene(self, needs_sync: Any = _UNSET) -> None:
        self.send({"cmd": "drawScene", "args": _make_args(needs_sync)})

    def draw_undo(self) -> None:
        self.send({"cmd": "drawUndo", "args": []})

    def enforce_backend_availability(self) -> None:
        self.send({"cmd": "enforceBackendAvailability", "args": []})

    async def get_annotations_json(self) -> Any:
        return await self._request("getAnnotationsJSON", [])

    async def get_clip_plane_depth_azi_elev(self, clip_plane_index: Any = _UNSET) -> Any:
        return await self._request("getClipPlaneDepthAziElev", _make_args(clip_plane_index))

    async def get_crosshair_pos(self) -> Any:
        return await self._request("getCrosshairPos", [])

    async def get_frame_4d(self, id: Any) -> Any:
        """Get the current 4D frame index for a volume.

        Parameters
        ----------
        id : string
            Volume ID (typically the URL or name)

        Returns
        -------
        number
            Current frame index (0-based), or 0 if volume not found
        """
        return await self._request("getFrame4D", _make_args(id))

    async def get_mesh_shader(self, mesh_index: Any) -> Any:
        return await self._request("getMeshShader", _make_args(mesh_index))

    async def get_tract_groups(self, mesh_index: Any) -> Any:
        """Get the group names for a tract mesh.

        Returns an empty array if the mesh is not a tract or has no groups.

        Parameters
        ----------
        mesh_index : number

        Returns
        -------
        string[]
        """
        return await self._request("getTractGroups", _make_args(mesh_index))

    async def get_volume_affine(self, volume_index: Any) -> Any:
        return await self._request("getVolumeAffine", _make_args(volume_index))

    async def get_volume_transform_info(self, name: Any) -> Any:
        """Get metadata for a specific volume transform (options, description, resultDefaults).

        Parameters
        ----------
        name : string

        Returns
        -------
        TransformInfo | undefined
        """
        return await self._request("getVolumeTransformInfo", _make_args(name))

    async def has_colormap(self, name: Any) -> Any:
        """Case-insensitive existence check for a registered colormap.

        Accepts
        whatever casing the caller has on hand (e.g. a lowercased `<select>`
        value) and compares against the canonical stored name. Prefer this
        over `nv1.colormaps.includes(...)` — it handles the first-letter
        canonicalization that `addColormap` and the filesystem auto-loader
        apply internally.

        Parameters
        ----------
        name : string

        Returns
        -------
        boolean
        """
        return await self._request("hasColormap", _make_args(name))

    def load_annotations_json(self, json: Any) -> None:
        self.send({"cmd": "loadAnnotationsJSON", "args": _make_args(json)})

    def load_deferred_4d_volumes(self, id: Any) -> None:
        """Load all remaining frames for a 4D volume that was opened with limitFrames4D.

        Re-fetches the complete file and replaces the truncated image data.

        Parameters
        ----------
        id : string
            Volume ID (typically the URL or name)
        """
        self.send({"cmd": "loadDeferred4DVolumes", "args": _make_args(id)})

    def load_document(self, source: Any) -> None:
        self.send({"cmd": "loadDocument", "args": _make_args(source)})

    async def load_drawing(self, source: Any) -> Any:
        return await self._request("loadDrawing", _make_args(source))

    def load_image(self, path_or_file: Any, options: Any = _UNSET) -> None:
        self.send({"cmd": "loadImage", "args": _make_args(path_or_file, options)})

    async def load_img_v1(self, volume_index: Any, is_flip_x: Any = _UNSET, is_flip_y: Any = _UNSET, is_flip_z: Any = _UNSET) -> Any:
        """Convert a float32 3-frame volume to V1 (eigenvector) RGBA representation.

        For formats like AFNI that lack NIfTI intent codes, this provides explicit
        conversion of vector field data (dim4=3, float32) to sign-encoded RGBA.

        Parameters
        ----------
        volume_index : number
            Index of the volume to convert
        is_flip_x : boolean
            Flip X component (default: false)
        is_flip_y : boolean
            Flip Y component (default: false)
        is_flip_z : boolean
            Flip Z component (default: false)

        Returns
        -------
        Promise<boolean>
        """
        return await self._request("loadImgV1", _make_args(volume_index, is_flip_x, is_flip_y, is_flip_z))

    def load_matcap(self, matcap_name: Any) -> None:
        self.send({"cmd": "loadMatcap", "args": _make_args(matcap_name)})

    def load_meshes(self, meshes: Any) -> None:
        self.send({"cmd": "loadMeshes", "args": _make_args(meshes)})

    def load_volumes(self, volumes: Any) -> None:
        self.send({"cmd": "loadVolumes", "args": _make_args(volumes)})

    def move_crosshair_in_vox(self, di: Any, dj: Any, dk: Any) -> None:
        self.send({"cmd": "moveCrosshairInVox", "args": _make_args(di, dj, dk)})

    def move_volume_down(self, volume_index: Any) -> None:
        """Move a volume down one index position in the stack of loaded volumes (toward the background).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeDown", "args": _make_args(volume_index)})

    def move_volume_to_bottom(self, volume_index: Any) -> None:
        """Move a volume to the bottom position in the stack of loaded volumes (index 0, background).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeToBottom", "args": _make_args(volume_index)})

    def move_volume_to_top(self, volume_index: Any) -> None:
        """Move a volume to the top position in the stack of loaded volumes (last index, top layer).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeToTop", "args": _make_args(volume_index)})

    def move_volume_up(self, volume_index: Any) -> None:
        """Move a volume up one index position in the stack of loaded volumes (toward the top layer).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeUp", "args": _make_args(volume_index)})

    def recalculate_cal_min_max(self, volume_index: Any, frame: Any = _UNSET) -> None:
        """Recalculate robust cal_min/cal_max for a specific 4D frame (or the current frame).

        Updates the volume's calibration range and triggers a GPU update.

        Parameters
        ----------
        volume_index : number
        frame : number | undefined
        """
        self.send({"cmd": "recalculateCalMinMax", "args": _make_args(volume_index, frame)})

    def refresh_drawing(self) -> None:
        """Mark the drawing texture as dirty and schedule a redraw.

        The expensive bitmap→RGBA conversion and GPU upload are deferred to
        the next animation frame, so rapid pointermove events only pay the
        cost once per frame.
        """
        self.send({"cmd": "refreshDrawing", "args": []})

    async def reinitialize_view(self, options: Any = _UNSET) -> Any:
        return await self._request("reinitializeView", _make_args(options))

    def remove_all_meshes(self) -> None:
        self.send({"cmd": "removeAllMeshes", "args": []})

    def remove_all_volumes(self) -> None:
        self.send({"cmd": "removeAllVolumes", "args": []})

    def remove_annotation(self, id: Any) -> None:
        self.send({"cmd": "removeAnnotation", "args": _make_args(id)})

    def remove_mesh(self, mesh_index: Any) -> None:
        self.send({"cmd": "removeMesh", "args": _make_args(mesh_index)})

    def remove_mesh_layer(self, mesh_index: Any, layer_index: Any) -> None:
        """Remove a scalar overlay layer from a mesh.

        Parameters
        ----------
        mesh_index : number
        layer_index : number
        """
        self.send({"cmd": "removeMeshLayer", "args": _make_args(mesh_index, layer_index)})

    def reset_volume_affine(self, volume_index: Any) -> None:
        self.send({"cmd": "resetVolumeAffine", "args": _make_args(volume_index)})

    def resize(self) -> None:
        self.send({"cmd": "resize", "args": []})

    async def save_bitmap(self, filename: Any = _UNSET, quality: Any = _UNSET) -> Any:
        return await self._request("saveBitmap", _make_args(filename, quality))

    def save_document(self, filename: Any = _UNSET) -> None:
        self.send({"cmd": "saveDocument", "args": _make_args(filename)})

    async def save_drawing(self, filename: Any = _UNSET) -> Any:
        return await self._request("saveDrawing", _make_args(filename))

    def save_mesh(self, mesh_index: Any, filename: Any = _UNSET, options: Any = _UNSET) -> None:
        self.send({"cmd": "saveMesh", "args": _make_args(mesh_index, filename, options)})

    async def save_volume(self, options: Any = _UNSET) -> Any:
        """Save voxel-based image to disk.

        Parameters
        ----------
        options : SaveVolumeOptions
            configuration object with the following fields:
            - `filename`: name of the NIfTI image to create. If empty, returns data only.
            - `isSaveDrawing`: whether to save the drawing layer or the background image
            - `volumeByIndex`: which image layer to save (0 for background)

        Returns
        -------
        Promise<boolean | Uint8Array>
            `true` if successful when writing to disk, or a `Uint8Array` if exported as binary data
        """
        return await self._request("saveVolume", _make_args(options))

    def select_annotation(self, id: Any) -> None:
        self.send({"cmd": "selectAnnotation", "args": _make_args(id)})

    async def serialize_document(self) -> Any:
        """Return the current scene serialized as an NVD document (CBOR-encoded Uint8Array).

        Returns
        -------
        Uint8Array
        """
        return await self._request("serializeDocument", [])

    def set_bounds(self, bounds: Any) -> None:
        """Update the drawing bounds for this Niivue instance.

        Coordinates use y=0 at bottom, y=1 at top (GL convention).

        Parameters
        ----------
        bounds : [number, number, number, number]
            [x1, y1, x2, y2] in normalized (0-1) coordinates.
            
            Example:
            nv.setBounds([0,0,0.5,0.5])   // bottom-left quarter
            nv.setBounds([0.5,0.5,1,1])   // top-right quarter
        """
        self.send({"cmd": "setBounds", "args": _make_args(bounds)})

    def set_clip_plane(self, depth_azimuth_elevation: Any) -> None:
        self.send({"cmd": "setClipPlane", "args": _make_args(depth_azimuth_elevation)})

    def set_clip_plane_depth_azi_elev(self, depth: Any, azimuth: Any, elevation: Any, clip_plane_index: Any = _UNSET) -> None:
        self.send({"cmd": "setClipPlaneDepthAziElev", "args": _make_args(depth, azimuth, elevation, clip_plane_index)})

    def set_clip_planes(self, depth_azi_elevs: Any) -> None:
        self.send({"cmd": "setClipPlanes", "args": _make_args(depth_azi_elevs)})

    def set_colormap_label(self, volume_index: Any, cmap: Any) -> None:
        """Set a label colormap on a volume (e.g., atlas/parcellation).

        Converts the ColorMap definition to an LUT and attaches it to the volume.
        When set, the orient shader uses nearest-neighbor label lookup instead of
        continuous colormap interpolation, and locationChange events include label names.

        Parameters
        ----------
        volume_index : number
            Index of the volume to apply the label colormap to
        cmap : ColorMap | null
            ColorMap definition with R,G,B arrays and optional labels/I arrays,
            or null to remove the label colormap
        """
        self.send({"cmd": "setColormapLabel", "args": _make_args(volume_index, cmap)})

    def set_colormap_label_from_url(self, volume_index: Any, url: Any) -> None:
        """Fetch a label colormap JSON from a URL or File and apply it to a volume.

        The JSON should contain R, G, B arrays and optional labels/I arrays.

        Parameters
        ----------
        volume_index : number
            Index of the volume to apply the label colormap to
        url : string | File
            URL string or File object pointing to a colormap JSON
        """
        self.send({"cmd": "setColormapLabelFromUrl", "args": _make_args(volume_index, url)})

    def set_connectome_options(self, mesh_index: Any, options: Any) -> None:
        """Update connectome extrusion/display options and re-extrude.

        Parameters
        ----------
        mesh_index : number
        options : Partial<NVConnectomeOptions>
        """
        self.send({"cmd": "setConnectomeOptions", "args": _make_args(mesh_index, options)})

    def set_crosshair_pos(self, pos: Any) -> None:
        self.send({"cmd": "setCrosshairPos", "args": _make_args(pos)})

    def set_drag_mode(self, mode: Any) -> None:
        self.send({"cmd": "setDragMode", "args": _make_args(mode)})

    async def set_font(self, font: Any) -> Any:
        """Swap the active font atlas.

        The font is infrastructure-level configuration
        (GPU-owned atlas texture + metrics map), so switching requires a full view
        rebuild — use this method instead of mutating `opts.font` directly.

        Parameters
        ----------
        font : NVFontData

        Returns
        -------
        Promise<boolean>
        """
        return await self._request("setFont", _make_args(font))

    async def set_font_from_url(self, urls: Any) -> Any:
        """Fetch an MSDF font atlas (PNG + JSON metrics pair) from URLs and swap it in as the active font.

        Useful for loading fonts that are not bundled
        with the library (e.g. the community atlases at
        https://github.com/niivue/fonts). The PNG URL is stored verbatim and
        used as the GPU atlas texture source.

        On failure (metrics fetch, view rebuild, or atlas texture upload)
        the previous font is restored so the view isn't left half-initialized.
        The original error is re-thrown after recovery.

        Parameters
        ----------
        urls : { atlas: string; metrics: string; }

        Returns
        -------
        Promise<boolean>
        """
        return await self._request("setFontFromUrl", _make_args(urls))

    def set_frame_4d(self, id: Any, frame: Any) -> None:
        """Set the current 4D frame for a volume.

        Parameters
        ----------
        id : string
            Volume ID (typically the URL or name)
        frame : number
            Frame index (0-based, clamped to valid range)
        """
        self.send({"cmd": "setFrame4D", "args": _make_args(id, frame)})

    def set_mesh(self, mesh_index: Any, options: Any) -> None:
        """Update display properties of a loaded mesh.

        Accepts any subset of mesh display options (opacity, shaderType, color, etc.)
        and triggers a single GPU update.

        Parameters
        ----------
        mesh_index : number
        options : MeshUpdate
        """
        self.send({"cmd": "setMesh", "args": _make_args(mesh_index, options)})

    def set_mesh_layer_frame_4d(self, mesh_index: Any, layer_index: Any, frame: Any) -> None:
        """Set the current 4D frame for a mesh layer.

        Parameters
        ----------
        mesh_index : number
        layer_index : number
        frame : number
        """
        self.send({"cmd": "setMeshLayerFrame4D", "args": _make_args(mesh_index, layer_index, frame)})

    def set_mesh_layer_property(self, mesh_index: Any, layer_index: Any, options: Any) -> None:
        """Update properties of a mesh layer (colormap, cal_min, cal_max, opacity, etc.).

        Triggers recompositing and GPU update.

        Parameters
        ----------
        mesh_index : number
        layer_index : number
        options : Partial<NVMeshLayer>
        """
        self.send({"cmd": "setMeshLayerProperty", "args": _make_args(mesh_index, layer_index, options)})

    def set_modulation_image(self, target_id: Any, modulator_id: Any) -> None:
        """Set a modulation image for a target volume.

        The modulator's intensity scales the target volume's brightness and opacity.

        Parameters
        ----------
        target_id : string
            ID of the volume to modulate
        modulator_id : string
            ID of the volume providing modulation (empty string to clear)
        """
        self.send({"cmd": "setModulationImage", "args": _make_args(target_id, modulator_id)})

    def set_tract_options(self, mesh_index: Any, options: Any) -> None:
        """Update tract tessellation/display options and re-tessellate.

        Parameters
        ----------
        mesh_index : number
        options : Partial<NVTractOptions>
        """
        self.send({"cmd": "setTractOptions", "args": _make_args(mesh_index, options)})

    def set_volume(self, volume_index: Any, options: Any) -> None:
        """Update display properties of a loaded volume.

        Accepts any subset of volume display options (colormap, opacity, cal_min, etc.)
        and triggers a single GPU update.

        Parameters
        ----------
        volume_index : number
        options : VolumeUpdate
        """
        self.send({"cmd": "setVolume", "args": _make_args(volume_index, options)})

    def set_volume_affine(self, volume_index: Any, affine: Any) -> None:
        self.send({"cmd": "setVolumeAffine", "args": _make_args(volume_index, affine)})

    def update_gl_volume(self) -> None:
        self.send({"cmd": "updateGLVolume", "args": []})

    async def vox2frac(self, vox: Any) -> Any:
        """Convert RAS voxel coordinates to scene fraction [0,1].

        Uses the background volume's matRAS for the vox→mm conversion.

        Parameters
        ----------
        vox : [number, number, number]

        Returns
        -------
        [number, number, number]
        """
        return await self._request("vox2frac", _make_args(vox))


